### ISSUE TITLE
SPAPT/mvt source annotation error

### ISSUE THREAD

**Issue by overrainbow** [brnorris03/Orio#20]
This annotation would cause the parser fail.
https://github.com/brnorris03/Orio/blob/3e35c3e3d51cb94539164df9609b3fe0178ec737/testsuite/SPAPT/mvt/mvt.ancc.src1.c#L49

It seems the file spec grammar is defined here:
https://github.com/brnorris03/Orio/blob/3e35c3e3d51cb94539164df9609b3fe0178ec737/orio/main/tspec/pparser.py#L126

Not sure why it fails. One easy fix is to move the let stmt into the def block as a statement to parse but not sure if that's what we want here.

**Comment by brnorris03** [comment]
If SIZE is an input parameter, then it should be moved to input_params just below -- not sure why it was left outside of a section, this must be old obsolete syntax. There shouldn't be things like that outside of sections.

**Comment by overrainbow** [comment]
Ok. I will make a PR to fix it. Thanks!
