### ISSUE TITLE
SPAPT/dgemv5 error

### ISSUE THREAD

**Issue by overrainbow** [brnorris03/Orio#22]
After removing the extra commas, the annotated dgemv.ancc.src5.c still throws the following exceptions in running. 

`ERROR: orio.module.loop.submodule.tile.transformation:: tile size (256) must be divisible by the stride value (512)
WARNING: orio.module.loop.submodule.tile.transformation: tile size 256 must be greater than the stride value 512; tile index = jjj`

**Comment by brnorris03** [comment]
That's a huge stride, is it correct? You can't have tile size smaller than it, for sure. Try decreasing the stride perhaps?
