### ISSUE TITLE
Fake loop id generation error

### ISSUE THREAD

**Issue by overrainbow** [brnorris03/Orio#24]
For some test code, Orio may not generate the fake id for nested loops properly (duplicated id). 

The following is one of the generated version for axpy:
```
 94 loop_42:
 95 for (int loop_42=0; loop_42 < 1; loop_42++) {
 96   register int cbv_1;
 97   cbv_1 = N - 1;
 98 #pragma ivdep
 99 #pragma vector always
100 loop_42:
101   for (int loop_42=0; loop_42 < 1; loop_42++) {
102     for (i = 0; i <= cbv_1; i++ )
103       y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i] + a4 * x4[i] + a5 * x5[i];
104     } // for (int loop_42=0; loop_42 < 1; loop_42++)
105 }
106 /*@ end @*/
```

Similar issue raised for MVT:

> .ERROR: orio.module.loop.submodule.composite.composite : error transforming "loop_80: 
  for (int loop_80=0; loop_80 < 1; loop_80++) {
    for (i = 0; i <= N - 1; i++ ) 
loop_80: 
      for (int loop_80=0; loop_80 < 1; loop_80++) {
        for (j = 0; j <= N - 1; j++ ) {
          x1[i] = x1[i] + a[i][j] * y_1[j];
          x2[j] = x2[j] + a[i][j] * y_2[i];
        }
        } // for (int loop_80=0; loop_80 < 1; loop_80++)
    } // for (int loop_80=0; loop_80 < 1; loop_80++)
"
 --> <type 'exceptions.TypeError'>:not all arguments converted during string formatting
ERROR: orio.module.loop.transformation:80: encountered an error during transformation of statement: "Composite"
 --> UnboundLocalError: local variable 'transformed_stmt' referenced before assignment
ERROR: orio.main.opt_driver: encountered an error during transformation <orio.module.loop.loop.Loop instance at 0x7f6426954290>:
 class TransformStmt has no attribute 'name'

**Comment by brnorris03** [comment]
fix committed in c14dbfe
